Notes.WebApi/Models/CreateNoteDto.cs
using AutoMapper;
using Notes.Application.Common.Mapping;
using Notes.Application.Notes.Commands.CreateNote;

namespace Notes.WebApi.Models
{
    public class CreateNoteDto : IMapWith<CreateNoteCommand> 
    {
        public string Title { get; set; }
        public string Details { get; set; }

        public void Mapping(Profile profile)
        {
            profile.CreateMap<CreateNoteDto, CreateNoteCommand>()
                .ForMember(noteCommand => noteCommand.Title, opt => opt.MapFrom(noteDto => noteDto.Title))
                .ForMember(noteCommand => noteCommand.Details, opt => opt.MapFrom(noteDto => noteDto.Details));
        }

    }
}

Notes.WebApi/Models/UpdateNoteDto.cs
using AutoMapper;
using Notes.Application.Common.Mapping;
using Notes.Application.Notes.Commands.UpdateNote;

namespace Notes.WebApi.Models
{
    public class UpdateNoteDto : IMapWith<UpdateNoteCommand> 
    {
       public Guid Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }

        public void Mapping(Profile profile)
        {
            profile.CreateMap<UpdateNoteDto, UpdateNoteCommand>()
                .ForMember(noteCommand => noteCommand.Title, opt => opt.MapFrom(updateDto => updateDto.Title))
                .ForMember(noteCommand => noteCommand.Details, opt => opt.MapFrom(updateDto => updateDto.Details))
                .ForMember(noteCommand => noteCommand.Id, opt => opt.MapFrom(updateDto => updateDto.Id));
               
        }
    }
}

Notes.WebApi/Controllers/Note/NoteController.cs
using MediatR;
using AutoMapper;

using Microsoft.AspNetCore.Mvc;
using Notes.Application.Notes.Queries.GetNoteDetails;
using Notes.Application.Notes.Queries.GetNoteList;
using Notes.WebApi.Models;
using Notes.Application.Notes.Commands.CreateNote;
using Notes.Application.Notes.Commands.UpdateNote;
using Notes.Application.Notes.Commands.DeleteCommand;

namespace Notes.WebApi.Controllers.Note
{
    
    public class NoteController : Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();

        private readonly IMapper mapper;
        public NoteController(IMapper _mapper)
        {

            mapper = _mapper;
        }

        
        [HttpGet]
        public async Task<ActionResult<NoteListVm>> GetAll()
        {
            var query = new GetNoteListQuery { };
            var vm = await Mediator.Send(query);
            return View(vm);

        }



        
        [HttpGet]
        public async Task<ActionResult<NoteDetailsVm>> Get(Guid id)
        {
            var query = new GetNoteDetailsQuery
            {

                Id = id
            };
            var vm = await Mediator.Send(query);
            return View(vm);
        }
       
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            return View();

        }

        
        [HttpPost]
        public async Task<ActionResult<Guid>> Create(CreateNoteDto createNoteDto)
        {
            var command = mapper.Map<CreateNoteCommand>(createNoteDto);

            var noteId = await Mediator.Send(command);
            return RedirectToAction("GetAll");

        }
        [HttpGet]
        public async Task<ActionResult> Update(Guid id)
        {
            var upd = new UpdateNoteDto { Id = id };
            return View(upd);
        }
       
        [HttpPost]
        public async Task<ActionResult> Update(UpdateNoteDto updateNoteDto)
        {

            var command = mapper.Map<UpdateNoteCommand>(updateNoteDto);
            await Mediator.Send(command);
            return RedirectToAction("Get", new { id = command.Id });
        }
       
        public async Task<ActionResult> Delete(Guid id)
        {
            var command = new DeleteNoteCommand
            {
                Id = id,

            };
            await Mediator.Send(command);
            return RedirectToAction("GetAll");
        }
    }



}

Notes.WebApi/Views/Note/Create.cshtml
@using Notes.WebApi.Models;
@model CreateNoteDto;
<div class="container">
<form method="POST" asp-controller="Note" asp-action="Create" enctype="multipart/form-data">
    <h2>Добавить новую заметку</h2>
    <div class="formItems">
        <div class="Inlines">
            <div class="Item">
                <label>Название</label>
                <input asp-for="Title" type="text" />
            </div>
            <div class="Item">
                <label>Описание</label>
                    <textarea asp-for="Details"></textarea>
            </div>
        </div>

        <div class="Blocked">
            <div class="ItemBlock BlockButt">
              
                <div>
                        <button class="createbtn"><input type="submit" /></button>
                       
                </div>
            </div>
        </div>
    </div>
</form>
    <a asp-action="GetAll"><button class="cancelbth">Отмена</button></a>
<div>

<style>
   
.container{
    
    background-color: #242424;
    border: none;
    border-radius: 30px;
    width: 45%;
    min-height: 30%;
    margin: 50px auto;
    font-family: TTtravelsRegular;
}
.container h2{
    color: white;
    margin-left: 30px;
    padding-top: 20px;
}
.formItems{
    
    
    margin-left: 30px;
    margin-top: 50px;
    color: white;
    font-weight: 200;
}
.Item label, input{
    display: block;
}
.Item{
    margin-bottom: 40px;
    
}

.Item:last-child{
    width: 190px;
}
input {
    border: none;
    border-bottom: 1px solid white;
    background-color: transparent;
    color: inherit;
    outline: none;
                text-decoration: none;
}
.ItemBlock input, textarea, select{
    display: block;
    resize: vertical;
}
.ItemBlock{
    margin-bottom: 40px;
}
textarea{
    background-color: #5F5F5F;
    border-radius: 6px;
    width: 637px;
    height: 223px;
}
select{
    background-color: #5F5F5F;
    color: black;
    height: 30px;
    border-radius: 6px;
}
.BlockButt{
    
}
.BlockButt button{
    padding: 10px 30px;
    border-radius: 20px;
    font-size: 13px;
    border: none;
    color: white;
}

.createbtn{
    background-color: #9F2525;
    
}
.cancelbth{
                padding: 10px 30px;
                border-radius: 20px;
                font-size: 13px;
                border: none;
                color: white;
                margin: 20px;
    background-color: #5F5F5F;
}
.cancelbth:hover{
    box-shadow:0 0 20px #5F5F5F;
}
.createbtn:hover{
    box-shadow:0 0 20px #9F2525;
}
</style>

Notes.WebApi/Views/Note/Get.cshtml
@using Notes.Application.Notes.Queries.GetNoteDetails;
@model NoteDetailsVm;

<div class="container">
    <h2>@Model.Title</h2>
    <div class="formItems">
        <div class="Blocked">
            <p style="font-size: 24px;">
               @Model.Details
            </p>
            <p style="font-size: 15px; margin-bottom: 2px">@Model.CreationDate - дата создания</p>
            @if(Model.EditDate != null){
                <p style="font-size: 15px; margin: 2px">@Model.EditDate - дата последнего редактирования</p>
            }
        </div>
    </div>
</div>
<div class="ItemBlock BlockButt">
    <div>
        <a asp-action="GetAll"> <button class="cancelbth">К списку</button></a>
    </div>
    <div>
        <a asp-action="Update" asp-route-id="@Model.Id"><button class="createbtn">Изменить</button></a>
    </div>
    <div>
        <a asp-action="Delete" asp-route-id="@Model.Id"><button class="delbtn">Удалить</button></a>
    </div>
</div>

<style>
    
.container{
    
    background-color: #242424;
    border: none;
    border-radius: 30px;
    width: 45%;
    min-height: 30%;
    margin: 50px auto;
    font-family: TTtravelsRegular;
}
.container h2{
    color: white;
    margin-left: 30px;
    padding-top: 20px;
}
.container img{
    width: 300px;
    height: 200px;
    margin-bottom: 40px;
}
.container p{
    margin-right: 10px;
}
.formItems{
    display: flex;
    flex-direction: row;
    gap: 40px;
    
    margin-left: 30px;
    margin-top: 50px;
    color: white;
    font-weight: 200;
}
.Item label, input{
    display: block;
}
.Item{
    margin-bottom: 40px;
    
}

.Item:last-child{
    width: 190px;
}
input {
    border: none;
    border-bottom: 1px solid white;
    background-color: transparent;
    color: inherit;
    outline: none;
}
.ItemBlock input, textarea, select{
    display: block;
    resize: vertical;
}
.ItemBlock{
    margin-bottom: 40px;
}
textarea{
    background-color: #5F5F5F;
    border-radius: 6px;
    width: 200px;
    height: 50px;
}
select{
    background-color: #5F5F5F;
    color: black;
    height: 30px;
    border-radius: 6px;
}
.BlockButt{
    margin: 10px 37%;
    display: flex;
    flex-direction: row;
    gap: 10px;
}
.BlockButt button{
    padding: 10px 30px;
    border-radius: 20px;
    font-size: 13px;
    border: none;
    color: white;
}
.createbtn{
    background-color: #9F2525;
}
.delbtn{
    background-color: #9F2525;
}
.cancelbth{
    background-color: #5F5F5F;
}
.cancelbth:hover{
    box-shadow:0 0 20px #5F5F5F;
}
.createbtn:hover{
    box-shadow:0 0 20px #9F2525;
}
.delbtn:hover{
    box-shadow:0 0 20px #9F2525;
}
</style>

Notes.WebApi/Views/Note/GetAll.cshtml
@using Notes.Application.Notes.Queries.GetNoteList;
@model NoteListVm;

    <h2>ВАШИ ЗАМЕТКИ</h2>
<div class="global_container">
    @foreach (var note in Model.Notes)
    {
        
        <div class="wrapper">
            <a asp-action="Get" asp-route-id="@note.Id">
                <div class="container">
                    <div class="bottom">
                        <div class="left">
                            <div class="details">
                                <h4>@note.Title</h4>
                                <p>@note.CreatedDate</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    
    }
</div>
<a asp-action="Create"><button>Добавить заметку</button></a>


<style>
    html, body {
        font-family: sans-serif;
        padding: 25px;
    }

    .global_container {
        display: flex;
        flex-direction: row;
        gap: 30px;
        flex-wrap: wrap;
        justify-content: space-around;
    }

    button {
        margin: 0 43%;
        background-color: #ce1919;
        width: 200px;
        height: 50px;
        color: white;
        font-size: 15px;
        border-radius: 30px;
        border: none;
    }

    .wrapper {
        width: 300px;
        
        background: white;
        margin: 20px 20px;
        position: relative;
        overflow: hidden;
        border-radius: 10px 10px 10px 10px;
        box-shadow: 0;
        transform: scale(0.95);
        transition: box-shadow 0.5s, transform 0.5s;
    }

    .container {
        width: 100%;
       
    }

    .top {
        height: 80%;
        width: 100%;
    }

    a {
        text-decoration: none;
        color: black;
    }

    .bottom {
        width: 200%;
        
        transition: transform 0.5s;
    }

    

    p {
        font-size: 10px;
    }

    .left {
        height: 100%;
        width: 50%;
        background: #f4f4f4;
        position: relative;
        float: left;
    }

    .details {
        padding: 20px;
        float: left;
        width: calc(70% - 40px);
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        gap: 50px;
        align-items: baseline;
    }

    .buy {
        float: right;
        width: calc(30% - 2px);
        height: 100%;
        background: #f1f1f1;
        border-left: solid thin rgba(0,0,0,0.1);
    }

    .right {
        width: 50%;
        background: #A6CDDE;
        color: white;
        float: right;
        height: 200%;
        overflow: hidden;
    }

    .done {
        width: calc(30% - 2px);
        float: left;
        transition: transform 0.5s;
        border-right: solid thin rgba(255,255,255,0.3);
        height: 50%;
    }

    .remove {
        width: calc(30% - 1px);
        clear: both;
        border-right: solid thin rgba(255,255,255,0.3);
        height: 50%;
        background: #BC3B59;
        transition: transform 0.5s;
    }
</style>

Notes.WebApi/Views/Note/Update.cshtml
@using Notes.WebApi.Models;
@model UpdateNoteDto;
<div class="container">
    <form method="POST" asp-controller="Note" asp-action="Update" enctype="multipart/form-data">
        <h2>Обновить заметку</h2>
        <div class="formItems">
            <div class="Inlines">
                <div class="Item">
                    <label>Название</label>
                    <input asp-for="Title" type="text" />
                </div>
                <div class="Item">
                    <label>Описание</label>
                    <textarea asp-for="Details"></textarea>
                </div>
            </div>

            <div class="Blocked">
                <div class="ItemBlock BlockButt">
                    <div>
                       
                    </div>
                    <div>
                        <button class="createbtn"><input type="submit" /></button>

                    </div>
                </div>
            </div>
        </div>
    </form>
    <a asp-action="Get" asp-route-id="@Model.Id"><button class="cancelbth">Отмена</button></a>
    <div>

        <style>

            .container {
                background-color: #242424;
                border: none;
                border-radius: 30px;
                width: 45%;
                min-height: 30%;
                margin: 50px auto;
                font-family: TTtravelsRegular;
            }

                .container h2 {
                    color: white;
                    margin-left: 30px;
                    padding-top: 20px;
                }

            .formItems {
               

                gap: 150px;
                margin-left: 30px;
                margin-top: 50px;
                color: white;
                font-weight: 200;
            }

            .Item label, input {
                display: block;
            }

            .Item {
                margin-bottom: 40px;
            }

                .Item:last-child {
                    width: 190px;
                }

            input {
                border: none;
                border-bottom: 1px solid white;
                background-color: transparent;
                color: inherit;
                outline: none;
            }

            .ItemBlock input, textarea, select {
               
                resize:vertical;
               
            }

            .ItemBlock {
               
            }

            textarea {
                background-color: #5F5F5F;
                border-radius: 6px;
                width: 637px;
                height: 223px;
            }

            select {
                background-color: #5F5F5F;
                color: black;
                height: 30px;
                border-radius: 6px;
            }

            .BlockButt {
                
            }

                .BlockButt button {
                    padding: 10px 30px;
                    border-radius: 20px;
                    font-size: 13px;
                    border: none;
                    color: white;
                }

            .createbtn {
                background-color: #9F2525;
            }

            .cancelbth {
                margin: 20px;
                background-color: #5F5F5F;
                padding: 10px 30px;
                border-radius: 20px;
                font-size: 13px;
                border: none;
                color: white;
            }

                .cancelbth:hover {
                    box-shadow: 0 0 20px #5F5F5F;
                }

            .createbtn:hover {
                box-shadow: 0 0 20px #9F2525;
            }
        </style>